---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwantz
  labels:
    app.kubernetes.io/name: qwantz
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: qwantz
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qwantz
    spec:
      containers:
        - name: qwantz
          image: qwantz
          env:
            - name: GOWON_BROKER
              value: mosquitto:1883
